### ISSUE TITLE
Cannot access class 'java9.util.concurrent.CompletableFuture'. Check your module classpath for missing or conflicting dependencies

### ISSUE THREAD

**Issue by rliuzzi** [Unleash/unleash-android-proxy-sdk#11]
We've attempted to update the SDK from 0.2.0 to 0.3.1 in the driver app and we got this error when rebuilding the project.  
We are using gradle 7.0.1 (which requires java11). I am sure it must be something project specific as it doesn't seem to be affecting the passenger app setup, but when looking at the SDK source I noticed there's an import with a reference to a java9 package when the project is compiled using java8 and perhaps that wasn't intentional? 

Thanks in advance for your taking a look!

```
> Task :base:data:compileDevDebugKotlin FAILED
e: /Users/vagrant/git/base/data/src/main/java/com/icabbi/driverapp/base/data/featureflag/UnleashFeatureFlagRepository.kt: (76, 24): Cannot access class 'java9.util.concurrent.CompletableFuture'. Check your module classpath for missing or conflicting dependencies
e: /Users/vagrant/git/base/data/src/main/java/com/icabbi/driverapp/base/data/featureflag/UnleashFeatureFlagRepository.kt: (85, 24): Cannot access class 'java9.util.concurrent.CompletableFuture'. Check your module classpath for missing or conflicting dependencies
e: /Users/vagrant/git/base/data/src/main/java/com/icabbi/driverapp/base/data/featureflag/UnleashFeatureFlagRepository.kt: (94, 24): Cannot access class 'java9.util.concurrent.CompletableFuture'. Check your module classpath for missing or conflicting dependencies

```

**Comment by chriswk** [comment]
Hi rliuzzi. Thanks for reporting this. We're using the retrofuture and we have added that as an `implementation` dependency, rather than an `api` dependency, which I'm guessing is the reason for the failure to resolve the library. the java9 package comes from the retrofuture library, it is provided as a reimplementation for backwards compatibility. I'll update our dependency configuration scope and push a `0.3.2` release today

**Comment by chriswk** [comment]
Could you please check whether or not the driver app has a dependency on "net.sourceforge.streamsupport:android-retrofuture:1.7.3", because as far as I understand the implementation scope should've been enough?

**Comment by rliuzzi** [comment]
Hey @chriswk , thanks for the response. Unfortunately we don't import it, I've run:
`./gradlew dependencies`
But there doesn't seem to be any conflicts. I've made a fork of this repo and made the change to build gradle declaration of retrofuture
`implementation -> api`
And the builds are working with no errors...I was also under the impression that implementation was enough, but it doesn't seem to be the case. 
Not sure why this is working for the passenger app, perhaps the project is importing the dependency from another lib?

**Comment by chriswk** [comment]
Ok, thanks for going to the trouble of confirming that implementation -> api solves your issue. I'll merge the fix and make a release, and the new version should be live on maven central by noon

**Comment by chriswk** [comment]
0.3.2 should not have the updated scope, and https://github.com/Unleash/unleash-android-proxy-sdk/actions/runs/1260774184 is performing the release to maven central. Once that's done, the mirrors will need to sync, so should be available before noon.
