### ISSUE TITLE
updateContext() function only updates refresh policy context without updating client context

### ISSUE THREAD

**Issue by JoshHughes-Nutmeg** [Unleash/unleash-android-proxy-sdk#13]
Calling `client.updateContext(newContext)` only updates the context for the internal refresh policy. it doesnt update the client's context. This is not obvious and can lead to potential issues

Work around is to manually call both:

```
client.unleashContext = newContext
client.updateContext(newContext).get() 
```

**Comment by chriswk** [comment]
Hi Josh. Good point, we should look into actually update the client's context as well, when using the updateContext().

Though, since the evaluation only happens in the proxy (so, when the client is refreshing), I would be surprised if it matters.

**Comment by jagtejsodhi** [comment]
Hey @chriswk, is this going to be handled soon?

**Comment by jagtejsodhi** [comment]
Bumping this as this is a very important issue that should be addressed asap.
