### ISSUE TITLE
Skip cache until fetching was tried at least once

### ISSUE THREAD

**Issue by afemu** [Unleash/unleash-android-proxy-sdk#15]
Hi,
I would like to enforce getting the values only from cache when polling was tried at least once. Currently I dont see a clean way to achieve this because the `AutoPollingPolicy` does silently skip if the fetcher failed and the error listener is not called in this case.

I am using flows to map the toggles to a more reactive approach and as soon as the first subscriber appears the client return `false` from cache followed by the response itself. I would like to have the subscribers wait until the first polling was tried.

Am I missing something here?

~~BTW: I saw configurable default values are already merged (#10), but theres no new version available yet. Any ETA on this one?~~

Thanks!

**Comment by vassilisimon** [comment]
+1

**Comment by chriswk** [comment]
Hi @afemu femu.

This fell through the cracks. I'll try to have a look next week. Alternately we would greatly appreciate a PR.

**Comment by afemu** [comment]
Sure. I created a PR #24 with the changes that I think might fix the problem.
