### ISSUE TITLE
different json parsers

### ISSUE THREAD

**Issue by schnaps1981** [Unleash/unleash-android-proxy-sdk#21]
hi team! 
it is possible to use different json parsers?
e.g. I use Moshi in my project, but unleash-sdk uses Jackson.

And it created some problem: filed "value" in object Toggle -> Variant -> Payload has JsonNode type, but Moshi does not support it.
`Payload(val type: String, val value: JsonNode)`

When i tried convert Toggle object to json (i want to save json string in file) i got IllegalArgumentException

`com.squareup.moshi.JsonDataException: java.lang.IllegalArgumentException: Cannot serialize abstract class com.fasterxml.jackson.databind.JsonNode
for class com.fasterxml.jackson.databind.JsonNode value
for class io.getunleash.data.Payload at $.ab-split-menu-tv-1.variant.payload`

sorry for my English :o)

**Comment by chriswk** [comment]
There's an argument to be made for providing a builder that allows you to pass in your own JSON parser. Some function that accepts a String and returns our base classes?

**Comment by schnaps1981** [comment]
i think that keep payload as string and\or convert it to other types good idea

**Comment by bogdanzurac** [comment]
The API shouldn't expose internally used libraries such as Jackson or any other 3rd party lib and should instead rely on primitives as much as possible. Pulling in this library in a project should enforce the user to pull in other dependencies as well.

**Comment by schnaps1981** [comment]
any news?

**Comment by gastonfournier** [comment]
Hi! I know this has been open for a while, but finally we managed to solve that in the new Android SDK: https://github.com/Unleash/unleash-android this one takes this feedback and avoids exposing internal libraries. There are other improvements as well and you can check this migration guide with the key things we found while migrating the sample app: https://github.com/Unleash/unleash-android/blob/main/docs/MigrationGuide.md

Resolving as the solution would be to migrate to the new SDK
