### ISSUE TITLE
Can't clear userId in UnleashContext after setting it.

### ISSUE THREAD

**Issue by jagtejsodhi** [Unleash/unleash-android-proxy-sdk#28]
### Describe the feature request

Clear/delete previously set userId in UnleashContext.

### Background

Using UnleashContext.Builder, I am able to set my user's id via the `userId(userId: String)`. However, when my user logs out, I want to clear the user id from the unleash context. 

### Solution suggestions

The API should take in a nullable user id `userId(userId: String?)` to handle this case.

**Comment by sjaanus** [comment]
Hey @jagtejsodhi . Would love to help you out, but can you please provide a little more info of why would you need something like this? If the user logs out, usually this means, the user has left using your application and you should need to worry about contexts that are not used anymore. :smiley:

**Comment by jagtejsodhi** [comment]
Hey @sjaanus, I don't think it's a great assumption to say "If the user logs out, usually this means, the user has left using your application and you should need to worry about contexts that are not used anymore.". For my app, as I'm sure when many others, a user can use the application in a logged out and logged in state. 

A user may continue to use the app after being logged out, and in this case, we want to ensure we are no longer tracking their userId.

**Comment by sjaanus** [comment]
Hey @jagtejsodhi That is excellent point. What is suggest to you at the moment is to create a new `UnleashContext` with `userId` as `null`. I will also add the suggestion to our backlog, so it will be possible to reuse the existing context and change the `userId` on the fly.

**Comment by jagtejsodhi** [comment]
Hey @sjaanus, I think we should reopen this issue. It's a really quick win and very important.
