### ISSUE TITLE
It should be possible to have the client report metrics

### ISSUE THREAD

**Issue by chriswk** [Unleash/unleash-android-proxy-sdk#3]
From https://docs.google.com/document/d/1BZkXSPobN6YYFrFwp9rcFT8pQCXbOWlDqPGmToqS0-s we know that part of the specification is to collate and report metrics so we should add the possibility to this client for doing that.

**Comment by chriswk** [comment]
Done in v0.2.0

**Comment by amit3vedi** [comment]
@chriswk metrics reporting is throwing 401 because SDK is not passing client key in header like `"Authorization" : "proxy-client-key"` or am i missing something?

**Comment by yjin** [comment]
Looks like not able to sending metrics reporting due to 401 Unauthorized and response:
{
	"type": "password",
	"path": "/auth/simple/login",
	"message": "You must sign in order to use Unleash",
	"defaultHidden": false
}

Have anyone been able to resolve it?

@amit3vedi Were you able to address the issue?
