### ISSUE TITLE
Cancel in flight toggle request before fetching a new one

### ISSUE THREAD

**Issue by jagtejsodhi** [Unleash/unleash-android-proxy-sdk#30]
### Describe the bug

If the `UnleashClient.updateContext` API is called multiple times in a row, the Unleash SDK sends out a feature toggle fetch for each `updateContext` call, without cancelling the prior in flight request. This leads to a race of network responses - whichever response comes back last will be the set of toggles added to cache. However, only the response from the last `updateContext` call should be the set of toggles added to cache.

### Steps to reproduce the bug

Call `updateContext` in a row 5 times with different user ids.
i.e.

```
unleashClient.updateContext(/* userId = 1 */)
unleashClient.updateContext(/* userId = 2 */)
unleashClient.updateContext(/* userId = 3 */)
unleashClient.updateContext(/* userId = 4 */)
unleashClient.updateContext(/* userId = 5 */)
```

### Expected behavior

The set of cached toggles should be the toggles returned for user with ID 5, since the latest call to updateContext set the user ID to 5.

### Logs, error output, etc.

```bash
In actuality, whichever of the 5 toggle responses finishes last will be the toggles that get cached.
```

### Additional context

Our suggestion - each time a new toggle fetch goes out, it should cancel any ongoing toggle fetch.

### Unleash version

0.4.1

### SDK information (language and version)

Android

**Comment by nunogois** [comment]
Hey @jagtejsodhi - Thanks for opening this issue! Let me reach out to the rest of the team and we'll get back to you 👍

**Comment by chriswk** [comment]
Hi @jagtejsodhi - This probably won't be prioritized for Q4. 

We do accept Pull Requests, so if you have a way to solve this, we'd happily review a PR.

Review our Contributing Guidelines here: https://github.com/Unleash/unleash/blob/main/CONTRIBUTING.md

**Comment by gastonfournier** [comment]
Hi @jagtejsodhi we have a new release of the Android SDK that takes this into account and it's also unit tested: https://github.com/Unleash/unleash-android/blob/5e0519afc35cfdc79fa6481c9cc24f0bdf91c683/unleashandroidsdk/src/test/java/io/getunleash/android/polling/UnleashFetcherTest.kt#L50

It's a brand new implementation so we wrote this migration guide: https://github.com/Unleash/unleash-android/blob/main/docs/MigrationGuide.md
