### ISSUE TITLE
Support multiple unleash instance in the same application

### ISSUE THREAD

**Issue by cchaouachi** [Unleash/unleash-android-proxy-sdk#37]
### Describe the feature request

Hello,

We are using multiple module in the same application android ,
Is it possible to have multiple unleash instance with different prox_url and proxy_key per module in the same application ?

**Comment by thomasheartman** [comment]
Hey, @cchaouachi 👋 In theory it might be possible, but it's most likely **not something you want to do**. Could you tell me more about the use case? I'm not sure what the need is? There may well be a better way to do what you're looking to achieve 😄

**Comment by cchaouachi** [comment]
Hey, @thomasheartman 

We are working on a sdk, which can be used by several android applications. 

And we need to add unleash to our sdk for our feature flipping , the host application may use unleash too so we need to be sure that unleash can support multiple instance  :)

**Comment by thomasheartman** [comment]
> We are working on a sdk, which can be used by several android applications.
> And we need to add unleash to our sdk for our feature flipping , the host application may use unleash too so we need to be sure that unleash can support multiple instance :)

I'm sorry, I still don't understand what exactly it is you're trying to do. What kind of SDK? 

And if you're talking about having multiple instances of the Unleash SDK running, then that will probably work, but it's not how it's intended to be used. Why do you need multiple instances? Could you explain the setup a little further?
