### ISSUE TITLE
Support for Kotlin Multiplatform

### ISSUE THREAD

**Issue by FranAguilarRod** [Unleash/unleash-android-proxy-sdk#42]
### Describe the feature request

Hi, I would like to use this library in a Kotlin Multiplatform project, is there any plan to support it?

Otherwise, will you accepts some PRs in order to migrate this library to Kotlin Multiplatform?

Thanks!

**Comment by pransh15** [comment]
Hi @FranAguilarRod 👋

Thank you for submitting the feature request. We are open to accepting PRs to migrate this to your use case, are you interested in taking this up?

**Comment by FranAguilarRod** [comment]
Perfect, I will take a look to the library and probably you will receive some PR soon 😄
