### ISSUE TITLE
Crash on Android 5

### ISSUE THREAD

**Issue by ehsan323** [Unleash/unleash-android-proxy-sdk#43]
### Describe the bug

After running on android 5, i got crash.

### Logs, error output, etc.

```bash
java.lang.NoClassDefFoundError: io.getunleash.metrics.HttpMetricsReporter$$ExternalSyntheticLambda1
        at io.getunleash.metrics.HttpMetricsReporter.log(MetricsReporter.kt:108)
```

### Unleash version

0.5.0

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

21

**Comment by vahid-m** [comment]
I have similar problem. The only workaround I found is that disable metrics on Android 5.1 and 6

**Comment by Tymek** [comment]
We will consider it closed. We are open for contributions, but we don't intend to provide more support for significantly out of date versions.
