### ISSUE TITLE
InvalidDefinitionException in release builds

### ISSUE THREAD

**Issue by jasonctoms** [Unleash/unleash-android-proxy-sdk#46]
### Describe the bug

In a release build, when trying to fetch toggles we see the exception `com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of io.getunleash.data.ProxyResponse (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)` inside of `getResponseAsync()`.

We have the following two lines in our proguard config, so things should be kept, but something is obviously missing.  Any ideas what could be wrong?

```
 -keep public class io.getunleash.** {*;}
 -keep class com.fasterxml.** {*;}
```

### Unleash version

Unleash Enterprise 5.0.1

### Subscription type

Enterprise

### Hosting type

Hosted by Unleash

### SDK information (language and version)

The kotlin Android SDK version 0.5.0

**Comment by thomasheartman** [comment]
Thanks for reporting this, @jasonctoms! I'll have one of our droid heads have look and get back to you 😄

**Comment by chriswk** [comment]
Hi @jasonctoms - Just verifying what we talked about in the [community slack](https://unleash-community.slack.com/archives/C023WTEM2BS/p1685084559323449). I'm confirming that we've seen your report, and this isn't the first time we've seen something similar. I'll make sure to carve out some time to fix this.

Will reach out to you to see if we can figure out the difference in the release build classpaths.

**Comment by jasonctoms** [comment]
After identifying some other R8 related issues in our repo that happened during the upgrade to gradle 8.0 and java 17, this problem seems to have gone away for us 🤐 So it appears this time it was with our R8 configuration.  I guess this issue can be closed, but thank you for the help!
