### ISSUE TITLE
TogglesUpdatedListener is not called when feature toggles have not changed since last sync

### ISSUE THREAD

**Issue by bogdanzurac** [Unleash/unleash-android-proxy-sdk#47]
### Describe the feature request

TogglesUpdatedListener (or another listener) should be triggered on every successful toggles fetch.

### Background

We have a use case in our apps in which we need to wait for the `UnleashClient` to be initialised and for it to fetch the feature toggles and only after that continue the initialisation of our app.

For this we rely on `TogglesErroredListener` and `TogglesUpdatedListener` listeners. However, `TogglesUpdatedListener` only triggers if the feature toggles have changed since last time they were fetched, as seen here:

```
if (response.isFetched() && cached != response.toggles) {
     super.writeToggleCache(response.toggles)
     this.broadcastTogglesUpdated()
}
```

That breaks our initialisation logic, because if the feature toggles have not changed since last fetch, the listener won’t be triggered, thus we don’t know that the `UnleashClient` has successfully fetched the toggles.

### Solution suggestions

Could the `TogglesUpdatedListener` (or even a completely separate listener) be triggered even when the feature toggles haven’t changed since last sync? What was the reasoning behind the current behaviour implementation?

**Comment by chriswk** [comment]
So. If I remember correctly, the thought behind the current logic is that the toggles haven't been updated, they were the same as in the last check.

You'd like an event broadcast on each fetch even if no updates have happened?

**Comment by bogdanzurac** [comment]
Yep, precisely.

**Comment by chriswk** [comment]
I'll see what I can do today.
