### ISSUE TITLE
Add possibility to not have polling at all inside the SDK

### ISSUE THREAD

**Issue by bogdanzurac** [Unleash/unleash-android-proxy-sdk#49]
### Describe the feature request

We have a use case in some of our applications where we don’t want to poll the Unleash Proxies at all. We need to only fetch the toggles when the app starts and then re-use the existing cached feature toggles for the current app session.

But the current architecture of the SDK doesn’t really allow for this use case. The best we could with the existing setup is to initialise the `UnleashConfig` with:

`AutoPollingMode(pollRateDuration = 2.days.inWholeMilliseconds, pollImmediate = false)`

And then manually trigger the refresh under the hood on the `UnleashClient` using:

`unleashClient.updateContext(unleashContext)`

However, just like mentioned in https://github.com/Unleash/unleash-android-proxy-sdk/issues/36, this doesn’t notify the `TogglesUpdatedListeners` after the new toggles are fetched.

### Solution suggestions

That being said, I think a more robust and flexible architecture would benefit the SDK, that would allow both polling and non-polling behaviours, depending on each developer’s use case. That way, we could initialise the `UnleashConfig` with something along the lines of `pollingMode(NoPollingMode)` and also add the possibility of manually trigger the initial refresh, just like it’s currently possible with `UnleashClient.startPolling()`.

Furthermore, I think that a `UnleashClient.cancelPolling()` would also benefit in scenarios such as: https://github.com/Unleash/unleash-android-proxy-sdk/issues/48, in order to have full control over the entire functionality of the SDK.

**Comment by chriswk** [comment]
Hi Bogdan. Added to our task board for the week. Will try to add a PR pretty soon.

**Comment by gastonfournier** [comment]
We have a new SDK https://github.com/Unleash/unleash-android where we took this into consideration: https://github.com/Unleash/unleash-android/pull/75.

There are some migration steps to get the new one explained here: https://github.com/Unleash/unleash-android/blob/main/docs/MigrationGuide.md
