### ISSUE TITLE
App Crashing on Android SDK < 26

### ISSUE THREAD

**Issue by PhilippeThibault** [Unleash/unleash-android-proxy-sdk#5]
It would seem the java.time.Duration is being used and causing the app to crash on android versions earlier than API 26.

```
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Duration;
        at io.getunleash.UnleashConfig$Builder.build(UnleashConfig.kt:97)
```

**Comment by ivarconr** [comment]
Thanks for reporting this. java.time.Instant seems to require API 26 as well. It should be relatively simple to replace all usage of Duration with just a simple long holding the ms-duration.

**Comment by ivarconr** [comment]
btw; is there any easy way we can declare API level support and make sure the package actually support that level?

**Comment by ivarconr** [comment]
I also saw this one. Would it be possible to build in support for durable in the Unleash SDK itself, our would this need to happen on the Android App level? 

https://developer.android.com/studio/write/java8-support#library-desugaring
