### ISSUE TITLE
v0.5.1 bumps Android minSdk to v26

### ISSUE THREAD

**Issue by bogdanzurac** [Unleash/unleash-android-proxy-sdk#54]
### Describe the bug

Version [0.5.1](https://github.com/Unleash/unleash-android-proxy-sdk/releases/tag/v0.5.1) inadvertently bumps the minimum supported Android SDK to v26, due to the Jackson library update that was made in https://github.com/Unleash/unleash-android-proxy-sdk/commit/60e5f6e75459b41e31043d70d5cdbaf6124098a8. 

Jackson versions above v2.14 have dropped support for Android under v26: https://github.com/FasterXML/jackson-databind/issues/3658

As mentioned inside the project README at https://github.com/Unleash/unleash-android-proxy-sdk#minimum-android-sdk, the minimum supported Android version should be v21.

### Screenshots

<img width="1667" alt="image" src="https://github.com/Unleash/unleash-android-proxy-sdk/assets/3236878/c864c6b5-a205-4df3-b184-8dd113ed6bc8">

### Unleash version

4.19.2

### Subscription type

Enterprise

### Hosting type

Self-hosted

### SDK information (language and version)

0.5.2

**Comment by Tymek** [comment]
Noted. We will try to fix that soon
