### ISSUE TITLE
Allow `isEnabled` to take a default flag argument

### ISSUE THREAD

**Issue by JoshHughes-Nutmeg** [Unleash/unleash-android-proxy-sdk#6]
Internally you return `false` if a toggle cant be found. I would like to be able to change the "fallback / default" value to be `true` for certain toggles.

**Comment by ivarconr** [comment]
makes sense. I think we should allow registration of a fallback function (similar to what we already have in the node-sdk). 

Be aware that a missing feature toggle might just mean it is not available with the current proxy configuration (project, tag filter etc).

**Comment by chriswk** [comment]
As we merged this PR, I'm closing this issue
