### ISSUE TITLE
The app name passed into UnleashConfig.Builder is not used at all from the SDK when adding the `appName` header.

### ISSUE THREAD

**Issue by StylianosGakis** [Unleash/unleash-android-proxy-sdk#67]
### Describe the bug

UnleashConfig and UnleashContext both have `appName` as a possible field inside of them.
However `AutoPollingPolicy` when it calls `updateToggles` it passes to the `getTogglesAsync` function of the fetcher only the `context`, not the unleashConfig. That means that then inside the fetcher, when `buildContextUrl` is called with the unleashContext, it is populated with `.addQueryParameter("appName", ctx.appName)`, so the appName from UnleashConfig is pretty much just not used at all in the query parameter.

### Steps to reproduce the bug

Setup the client using UnleashConfig.newBuilder().appName("...")
Try to use the SDK and notice that the app name is not passed along in the network request

### Expected behavior

That the appName does not need to be passed into the UnleashContext, and that the config builder either removes this API completely, or that it is taken into consideration as well

### Unleash version

0.5.7

### Subscription type

Open source

### Hosting type

Self-hosted

**Comment by andreas-unleash** [comment]
Hi @StylianosGakis .  Thanks for bringing this to our attention.  I will triage this with the team and get back to you
