### ISSUE TITLE
It is impossible to remove added listeners that are trying to listen in on changes to the feature flags

### ISSUE THREAD

**Issue by StylianosGakis** [Unleash/unleash-android-proxy-sdk#68]
### Describe the feature request

I would like to be able to remove the listeners, as we can very quickly go overboard with adding a lot of new listeners for every time we start a subscription to a specific feature flag.

### Background

We got a convenience function in our codebase which allows us to read all feature flag change triggers returning a `Flow<Unit>` by doing something like this:
```
fun foo(): Flow<Unit> = callbackFlow {
  trySend(Unit)
  val listener = TogglesUpdatedListener {
    trySend(Unit)
  }
  unleashClient.addTogglesUpdatedListener(listener)
  awaitClose {
    // unleashClient.removeTogglesUpdatedListener(listener)
  }
}
```
But we can not remove the listener as soon as the flow is killed and we are no longer interested in the result, since `removeTogglesUpdatedListener` does not exist right now.

### Solution suggestions

Add a pairing `removeTogglesUpdatedListener` function to match the `addTogglesUpdatedListener` function.

**Comment by nunogois** [comment]
Hi @StylianosGakis, thanks for raising this issue. We'll have a look and get back to you soon!

**Comment by StylianosGakis** [comment]
Hey, I also raised a PR to accompany this which I would appreciate if you take a look at 😊 if you agree with the implementation you won't even have to prioritize this, it's done 😅
