### ISSUE TITLE
Metrics should not require manual enabling

### ISSUE THREAD

**Issue by sighphyre** [Unleash/unleash-android-proxy-sdk#74]
### Describe the feature request

This SDK requires manually opting into metrics. This is different from other Unleash SDKs

### Background

This is very easy to miss and if you're used to using other Unleash SDKs, you won't notice that you've missed it

### Solution suggestions

Make this opt out instead

**Comment by gastonfournier** [comment]
The new SDK has metrics enabled by default: https://github.com/Unleash/unleash-android/blob/main/docs/MigrationGuide.md
