### ISSUE TITLE
Metrics API returns 404 if proxy/all is used

### ISSUE THREAD

**Issue by vitoksmile** [Unleash/unleash-android-proxy-sdk#77]
### Describe the bug

If we want to receive a list of all feature flags (enabled + disabled) we have to use `proxy/all` endpoint, but in that case metrics API returns 404 because of `baseUrl`/`proxyUrl` containing `all`.

404 `/proxy/all/client/metrics`
Cannot POST /proxy/all/client/metrics

### Steps to reproduce the bug

1. Set baseUrl as `proxy/all`
2. Wait for 1 minute (default metrics inverval)

### Expected behavior

We shoud have possibility to use `proxy/all` and `metrics` APIs

### Logs, error output, etc.

```bash
404 .../proxy/all/client/metrics

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /proxy/all/client/metrics</pre>
</body>
</html>
```

### Unleash version

5.12.4

### Subscription type

Enterprise

### Hosting type

Self-hosted

### SDK information (language and version)

1.0.0

**Comment by ivarconr** [comment]
Hi, 

are you using Unleash Edge or Proxy?

**Comment by vitoksmile** [comment]
> Hi, 
> 
> are you using Unleash Edge or Proxy? 

we are using Proxy

**Comment by ivarconr** [comment]
The proxy lacks that end-point. However if you use [Unleash Edge](https://github.com/Unleash/unleash-edge/tree/main) it is already supported. 

The proxy is currently in maintenance mode, and we encourage all users to migrate to Edge when they have a chance.

**Comment by HenrikBacher** [comment]
To jump in here as a coworker to @vitoksmile - We would like to migrate to using Unleash Edge, but it's not a feature parity yet [Unleas Edge - not supported](https://github.com/Unleash/unleash-edge/blob/main/migration-guide.md#not-supported). In our setup we a relying on context enrichers in the Proxy, hence we won't be able to migrate before that is supported
