### ISSUE TITLE
Getting error java.lang.NoClassDefFoundError: Failed resolution of: Lorg/slf4j/LoggerFactory; at io.getunleash.UnleashClient.<clinit>(UnleashClient.kt:82)

### ISSUE THREAD

**Issue by daniel-waiguru** [Unleash/unleash-android-proxy-sdk#78]
### Describe the bug

I am getting this error on release build java.lang.NoClassDefFoundError: Failed resolution of: Lorg/slf4j/LoggerFactory; at io.getunleash.UnleashClient.<clinit>(UnleashClient.kt:82) while trying to instantiate unleash client

### Steps to reproduce the bug

1. Add unleash dependency
2. Add proguard rules
3. Create unleash client on app startup
4. Launch release build app
5. App crashes with the error above issue seem to be Logger used in UnleashClient

### Expected behavior

Unleash client should be created with app crash

### Logs, error output, etc.

```bash
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/slf4j/LoggerFactory;
                                                                                                    at io.getunleash.UnleashClient.<clinit>(UnleashClient.kt:82)
```

### Unleash version

1.0.0

### Subscription type

Enterprise

### Hosting type

Hosted by Unleash

### SDK information (language and version)

Mobile SDK version 1.0.0

**Comment by gastonfournier** [comment]
We've launched a new SDK https://github.com/Unleash/unleash-android which does not use SLF4J and leans on native Android logging. 

This is a migration guide: https://github.com/Unleash/unleash-android/blob/main/docs/MigrationGuide.md
